version: "3.7"

services:
  mongo1:
    image: mongo
    # ports:
    #   - 27017
    volumes:
      - ./mongo1:/data/
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo2:
    image: mongo
    # ports:
    #   - 27017
    volumes:
      - ./mongo2:/data/
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo3:
    image: mongo
    # ports:
    #   - 27017
    volumes:
      - ./mongo3:/data/
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongoreplica:
    image: mongo-express
    restart: always
    ports:
      - 27016:8081
    environment:
      - "ME_CONFIG_BASICAUTH_USERNAME=admin"
      - "ME_CONFIG_BASICAUTH_PASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0"
      - "ME_CONFIG_OPTIONS_EDITORTHEME=cobalt"

  mongosetup:
    build: .
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongosetup:/data/

volumes:
  mongo1:
  mongo2:
  mongo3:
  mongosetup:
